name: node-refresh
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: run node refresh
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/ednovas.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/sspool.herokuapp.com/bihai.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/sspool.herokuapp.com/ednovas.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/sspool.herokuapp.com/provider-other.yaml
      - run: curl https://purge.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml
      - run: curl https://purge.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy_Classical.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/ruleset/mydirect.yaml
      - run: curl https://purge.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
      - run: curl https://purge.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/ruleset/proxyme.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/ruleset/GTA-R.yaml
      - run: curl https://purge.jsdelivr.net/gh/lcx12901/v2ray-@master/ruleset/baha.yaml
      - run: curl https://purge.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hijacking/Hijacking_Resolve.yaml
      - run: curl https://purge.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical_Resolve.yaml
